### ISSUE TITLE
Published groupId differs from Maven groupId

### ISSUE THREAD

**Issue by moberwasserlechner** [kenglxn/QRGen#103]
I wanted to build and install QRGen to my local maven repo to test a feature I'm working on and realised that the groupId in the published version on jitpack differs from the one used in Maven.

To get the dependency from Jitpack I use:
```
compile 'com.github.kenglxn.QRGen:javase:2.5.0'
```

To get the snapshot with my features from mavenLocal() I use:
```
compile 'net.glxn.qrgen:javase:2.6.0-SNAPSHOT'
```

I'm happy to create a pull request and fix this to `com.github.kenglxn.QRGen` but need your approval.

**Comment by kenglxn** [comment]
resolved in #104
