### ISSUE TITLE
Failed to get com.google.zxing by gradle

### ISSUE THREAD

**Issue by YSArch** [kenglxn/QRGen#106]
Following the steps by https://github.com/kenglxn/QRGen/ 

 +--- com.github.kenglxn.QRGen:javase:2.5.0
|              |    +--- com.google.zxing:javase:3.3.0 FAILED
|              |    \--- com.github.kenglxn.QRGen:core:2.5.0
|              |         \--- com.google.zxing:core:3.3.0 FAILED

There is a problem to grasp dependencies of com.google.zxing.

**Comment by YSArch** [comment]
In  javase-2.5.0.pom:
  <dependency>
      <groupId>com.google.zxing</groupId>
      <artifactId>javase</artifactId>
    </dependency>
There is no version specified, is that the cause?

**Comment by kenglxn** [comment]
There is not enough information here for anyone to be able to help you.

You should add the following:
What does you build look like? (show your gradle og pom file). 
What is the output from the build? (log)


Closing this as it is unlikely a problem with QRGen.
Feel free to reopen if it indeed is a problem with QRGen. Perhaps there is room for improvement in the readme. If so can you specify what is misleading or wrong?
