### ISSUE TITLE
Unable to extend Schema for Custom Schema

### ISSUE THREAD

**Issue by nflynn-rm** [kenglxn/QRGen#108]
Hi,

I am trying to create a custom Schema in my own project and I am unable to do so due to the following error:

 `Schema() is not public in Schema; cannot be accessed from outside package`

Is there a way around this that I am not seeing or could someone point me in the right direction, please?

**Comment by kenglxn** [comment]
A bit hard to tell what's wrong from that message alone, but it sounds like the compiler is telling you to add a no-args public constructor. 
What does your implementation look like?

you can take a look at one of the Schema implementations in QRGen for example SMS https://github.com/kenglxn/QRGen/blob/master/core/src/main/java/net/glxn/qrgen/core/scheme/SMS.java

**Comment by nflynn-rm** [comment]
Sorry I should have posted an example.

    public class CustomSchema extends Schema {
    
        CustomSchema() {
            super();
        }
    
        @Override
        public Schema parseSchema(String code) {
            return null;
        }
    
        @Override
        public String generateString() {
            return null;
        }
    }


The compiler is complaining about the super() call, saying that:
 
    Schema() is not public in "net.glxn.qrgen.core.scheme.Schema". Cannot be accessed from outside package

**Comment by kenglxn** [comment]
Ok. Sounds like maybe you are hitting a bug that was fixed a while back. 
Looks like I have forgotten to make a new release with the bugfix. Until I do, you can use the latest master from jitpack. Should solve the issue for you: https://jitpack.io/#kenglxn/QRGen/master-2.4.0-gf2bc9c6-3, 
bugfix: https://github.com/kenglxn/QRGen/pull/105

**Comment by nflynn-rm** [comment]
Great, that seems to have solved the problem.

Thanks for your help!

**Comment by kenglxn** [comment]
reopening this. will close once release is made
