### ISSUE TITLE
Bitmap creator

### ISSUE THREAD

**Issue by vinayjaiswal** [kenglxn/QRGen#114]
Bitmap creator method is missing in code, please check

**Comment by atomfrede** [comment]
Are you using android? `bitmap()` is only available on android.

**Comment by kenglxn** [comment]
closing this. bitmap is only available on android. If there is an issue with bitmap on android feel free to reopen.

**Comment by creativetrendsapps** [comment]
bitmap() does work on android

**Comment by AlexisN94** [comment]
I'm using android and having the same issue.
