### ISSUE TITLE
White space around QR Code

### ISSUE THREAD

**Issue by georgethomas2015e** [kenglxn/QRGen#116]
How to remove or decrease the white space around the generated QR code.

Bitmap qrcodeBitmap = QRCode.from("Hello").withSize(1500, 1500).bitmap();
        qrcodeimage.setImageBitmap(qrcodeBitmap);

**Comment by kenglxn** [comment]
see https://github.com/kenglxn/QRGen/issues/109

**Comment by fabioebner** [comment]
Still not working  I using this code: `return QRCode.from(conteudo).withSize(qrCodeWidth,qrCodeHeight).withHint(EncodeHintType.MARGIN, 0).withCharset("UTF-8").file();` I already try 1 but without success

and get this result: look the diference with the right qrCode (without margin)

![Screen Shot 2019-04-11 at 15 34 16](https://user-images.githubusercontent.com/2648675/55982468-547b4200-5c6f-11e9-9c24-cad1a1bacb2a.png)
