### ISSUE TITLE
how can i add a text specification on the top or bottom

### ISSUE THREAD

**Issue by wzhsh90** [kenglxn/QRGen#117]
Hi：

example:
![2018082117364527](https://user-images.githubusercontent.com/16187191/48065370-732f6580-e205-11e8-81e1-2d3bddfa9563.png)

**Comment by kenglxn** [comment]
Placing text below an image can be done in many different ways depending on your target medium. I do not see how this is applicable to QRGen though. 

My suggestion is to take the generated qrcode and place text below or above using the layout options available in the target medium. for instance using appropriate html markup or layout markup for android.
