### ISSUE TITLE
JitPack dependencies missing

### ISSUE THREAD

**Issue by brianlenz** [kenglxn/QRGen#125]
Sorry if this isn't the best way to let you know, but we discovered your 2.2.0 and 2.3.0 core dependencies are currently missing from the JitPack repo:

https://jitpack.io/com/github/kenglxn/qrgen/core/2.2.0/
https://jitpack.io/com/github/kenglxn/qrgen/core/2.3.0/

2.1.0 and 2.4.0 are working properly, however.

Thanks for providing QRGen! 👍

**Comment by kenglxn** [comment]
Thanks for letting me know. I will look into it.

**Comment by kenglxn** [comment]
I have submitted an issue with jitpack.

**Comment by kenglxn** [comment]
I’m waiting for github package registry to land. that will resolve this issue.
