### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by blacelle** [kenglxn/QRGen#127]
Hello. When do you plan to release next version? There is multiple interesting new features available since latest release, including SVG support.

Thanks

**Comment by kenglxn** [comment]
https://github.com/kenglxn/QRGen/releases/tag/2.6.0

**Comment by kenglxn** [comment]
I know there are some issues with jitpack, I am still waiting/looking for a viable alternative. Hopefully github package registry will be available soon.

https://github.com/kenglxn/QRGen/issues/125

**Comment by kenglxn** [comment]
Please let me know if you are able to get 2.6.0, if not we will have to find a workaround in the interim.
