### ISSUE TITLE
ColorRes option

### ISSUE THREAD

**Issue by TurKurT656** [kenglxn/QRGen#131]
TnQ for this lib,
How we can set a color from color res id or color attr?
like this:
.withColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary))

**Comment by kenglxn** [comment]
not sure. QRGen is just a wrapper on top of ZXING(https://github.com/zxing/zxing) 
If it can be done in zxing, then we should be able to do it with QRGen as well. Try checking the docs of zxing.

**Comment by TurKurT656** [comment]
is there any method that convert that to 0xAARRGGBB format?

**Comment by Dagzo** [comment]
I think you can set a color from res id like below.
Please try it.

``` 
.withColor(ContextCompat.getColor(getActivity(), R.color.colorPrimary), Color.WHITE)
```
