### ISSUE TITLE
[Feature Request] Possibility to add custom logo

### ISSUE THREAD

**Issue by eximius313** [kenglxn/QRGen#132]
Could you please add possibility to add custom logo?

This website has really powerful customization options - https://www.qrcode-monkey.com/ - it would be great if QRGen support at least some of them

Kind regards

**Comment by QuadStingray** [comment]
@kenglxn Any informations how to use that? Or is that not implemented?

**Comment by kenglxn** [comment]
> @kenglxn Any informations how to use that? Or is that not implemented?

No, It is not implemented.
It may be possible if there was an api to get a `BufferedImage` from qrgen. 
Something like: 
```
public BufferedImage bufferedImage() {
        try {
            return MatrixToImageWriter. toBufferedImage(createMatrix(text), matrixToImageConfig);
        } catch (WriterException e) {
            throw new QRGenerationException("Failed to create QR image from text due to underlying exception", e);
        }
    }
```

Then do something like what [this article](https://aboullaite.me/generate-qrcode-with-logo-image-using-zxing/) describes

**Comment by eximius313** [comment]
So why this issue has been closed? Isn't it possible to add proper API do QRGen?

**Comment by kenglxn** [comment]
sure it is possible. Feel free to submit a PR.
