### ISSUE TITLE
Incorrect checksum for v2.6.0

### ISSUE THREAD

**Issue by KMahoney** [kenglxn/QRGen#137]
I'm not very familiar with Java packaging so forgive me if this is the wrong place to report this, but I have been experiencing failing builds because the checksum for 2.6.0 on jitpack.io seems to be incorrect.

This might not affect many of your users because Maven doesn't check checksums, but Coursier does.

```
  Error while fetching artifact with coursier: Error fetching artifacts:
https://jitpack.io/com/github/kenglxn/QRGen/core/2.6.0/core-2.6.0.jar: wrong checksum: v1/https/jitpack.io/com/github/kenglxn/QRGen/core/2.6.0/core-2.6.0.jar (expected SHA-1 766e1d60e69b8764f5d6879540e93eb3fb537205 in v1/https/jitpack.io/com/github/kenglxn/QRGen/core/2.6.0/core-2.6.0.jar.sha1, got c7d01630bfb5450ca17ceb897846dc2fa36ca198)
https://jitpack.io/com/github/kenglxn/QRGen/android/2.6.0/android-2.6.0-sources.jar: wrong checksum: v1/https/jitpack.io/com/github/kenglxn/QRGen/android/2.6.0/android-2.6.0-sources.jar (expected SHA-1 2c2b82a70eaf56713a41efabe7437b05e3072608 in v1/https/jitpack.io/com/github/kenglxn/QRGen/android/2.6.0/android-2.6.0-sources.jar.sha1, got 55a40e057a19d70e67183e235d19e9570f09e3dd)
```

**Comment by ligi** [comment]
just experienced the same - wondering if this is a @jitpack-io problem. But the first time I experienced something like this - and a bit careful as the app where I enabled checksum checking is a bit sensitive.

**Comment by ligi** [comment]
Some more information: I compared the files - the only differences are in ./META-INF/MANIFEST.MF and ./META-INF/maven/com.github.kenglxn.QRGen/core/pom.properties

```
< a3595d7ac5969fc24931875cc2ab89ebd54d5947349a2a050fee1fda4aa904fc4cf0a220815c5018bfdf84abe27e9813049c51b7f6f76b7e731cdbb24d30bd78  ./META-INF/MANIFEST.MF
---
> cd80977848a2e06e322fa7d88e0ba490140f232ead9bdff868ce259b3b01e9408b4158e31e963e2c33c6cd3dddf791e4992e5a10ed09dbcfa7112cbd1b67ffcf  ./META-INF/MANIFEST.MF
3c3
< 3d0a55b14d22b6029e5b6a05fb2f6ada38d17a8e3983654946e39dada1151bf137b70be712dfed96aba2fa5c1a429e0bca96652cc0ef5dd7b5d5f7b89800995e  ./META-INF/maven/com.github.kenglxn.QRGen/core/pom.properties
---
> 5bf9089e1fa7e62174a65af42b06db66e46e23df375fe68b6e54b7503592305d62cb0d45c09e87847e2bf94199b68e17d099f4319b482c991d433c0317dd5be1  ./META-INF/maven/com.github.kenglxn.QRGen/core/pom.properties

```
```
ligi@ligi-p1:~/tmp/checksum-problem/2$ diff META-INF/MANIFEST.MF ../1/META-INF/MANIFEST.MF 
5c5
< Build-Jdk: 1.8.0_212
---
> Build-Jdk: 1.8.0_252
```

```
ligi@ligi-p1:~/tmp/checksum-problem/2$ diff META-INF/maven/com.github.kenglxn.QRGen/core/pom.properties ../1//META-INF/maven/com.github.kenglxn.QRGen/core/pom.properties
2c2
< #Thu Jul 18 09:47:01 UTC 2019
---
> #Sat Jan 30 10:02:58 UTC 2021

```

--> so it should be safe to use this version - still wonder what triggered the rebuild @jitpack-io

**Comment by kenglxn** [comment]
thanks for reporting and checking this out. I will look into getting the maven central pipeline up again when I have som spare time.

**Comment by jitpack-io** [comment]
Hi all,

We have now restored the previous versions of core-2.6.0.jar and android-2.6.0-sources.jar so the checksums should be matching. In January we had a user asking why QRGen is not available and we had trouble accessing our long term object storage (like S3). The quickest way was to rebuild and that's what we did. It doesn't change the functionality but the downside is that checksums don't match. Sorry for the confusion.

**Comment by kenglxn** [comment]
@jitpack-io thanks for the follow up :)

**Comment by ligi** [comment]
@jitpack-io did it happen again? Just got this checksum issue:

```
Actual checksum is [360DA41EF035D204CD355FD3E1BE34894E2018878A073881556AD8AFEC374CAF2BFAD0B47B0AF91A4A1A02A343780F1625C1D2FCE026D112121B54096A991666], however expected one of [864A866A36BFECF7372CF50ACACCBEE87266ACB4F7E2A1D4155D27161FD4870F89FB8EBE8F42DACD284A8BCC1C27D4F976F1800D7F51B97C57CDF9F291CB10C1]:
      com.github.kenglxn.QRGen:android:2.6.0 (pgp=[], sha512=[360DA41EF035D204CD355FD3E1BE34894E2018878A073881556AD8AFEC374CAF2BFAD0B47B0AF91A4A1A02A343780F1625C1D2FCE026D112121B54096A991666])

```

**Comment by philipwhiuk** [comment]
Seen this recently as well for the javase module...
