### ISSUE TITLE
Java Bitmap not found in QRGen

### ISSUE THREAD

**Issue by dryasbk** [kenglxn/QRGen#139]
Bitmap myBitmap = QRCode.from("www.example.org").bitmap();

In java android studio. bitmap() appear red and state that bitmap is not found

**Comment by MohamedHarmoush** [comment]
@dryasbk  Use the dependency 
implementation 'com.github.kenglxn.QRGen:android:2.6.0'
instead of implementation 'com.github.kenglxn.QRGen:javase:2.6.0'
