### ISSUE TITLE
Next release plans

### ISSUE THREAD

**Issue by philipwhiuk** [kenglxn/QRGen#148]
With the updates to batik etc is there any plan for a patch release?

**Comment by kenglxn** [comment]
feel free to make a PR and I will look it over.

**Comment by Lonzak** [comment]
[Done](https://github.com/kenglxn/QRGen/pull/151)

**Comment by kenglxn** [comment]
[3.0.0](https://github.com/kenglxn/QRGen/releases/tag/3.0.0) is relased and should be available now 
* https://github.com/kenglxn/QRGen/pull/151/
* https://github.com/kenglxn/QRGen/pull/153
