### ISSUE TITLE
No vector formats available

### ISSUE THREAD

**Issue by sytolk** [kenglxn/QRGen#40]
no vector graphic formats EPS or SVG available.
I want to have QR image with vector format for better print quality. Something like:
QRCode.from("Hello World").to(ImageType.SVG).withSize(250, 250).file();

**Comment by atomfrede** [comment]
@sytolk You can try the latest snapshot with update api. 
@kenglxn I would consider this issue as done

**Comment by kenglxn** [comment]
Thanks @atomfrede, forgot to close this after i merged.
