### ISSUE TITLE
Java 6 is not supported?

### ISSUE THREAD

**Issue by rickdong** [kenglxn/QRGen#49]
Was getting the following error:

Caused by: java.lang.UnsupportedClassVersionError: net/glxn/qrgen/javase/QRCode : Unsupported major.minor version 51.0

**Comment by atomfrede** [comment]
Minimum required java version is java 7.

**Comment by atomfrede** [comment]
@kenglxn I think you should close this issue. Java 7 is now end of life, so why trying to support java 6...

**Comment by kenglxn** [comment]
You could try to build from source, but qrgen is currently java7. java 7 will be EOL very soon as well.
