### ISSUE TITLE
problem with bitmap

### ISSUE THREAD

**Issue by MuhamedFathy** [kenglxn/QRGen#50]
I can't use any method in the library with the bitmap, only the given example in read me works, but if i want to add some methods like `withCharset()` or `withWidth()` it's just give me error!

for example:
`final Bitmap bm = QRCode.from(et.getText().toString()).bitmap();` <-- That's works!

`final Bitmap bm = QRCode.from(et.getText().toString()).withSize(600, 600).withCharset("UTF-8").bitmap();` <-- Not working!

Also the `withColor()` method don't work in general!

Am new in programming actually and don't know how to use that or is this is a serious issue or not!

**Comment by atomfrede** [comment]
Which version are you using? The feature to use bitmap with other operations was just added a few weeks ago.

**Comment by MuhamedFathy** [comment]
Actually I added that in my app gradle 
`dependencies {
    compile ("net.glxn.qrgen:android:2.0")
}`
 and I think that's the latest version, right?
Also I don't know what is maven and how to use it with my app (as I said, I'm newbie in that field).

**Comment by atomfrede** [comment]
maven is a repository where libraries can be published. So you're using the current, stable version. Just add the snapshot repository (as described in the readme) to your ``gradle`` build file and use ``2.1-SNAPSHOT`` instead of ``2.0``

**Comment by MuhamedFathy** [comment]
@atomfrede 
Now i added the repo as you said and changed the version like that...

![selection_001](https://cloud.githubusercontent.com/assets/4931115/7522533/7c03685c-f4fe-11e4-82d4-17dc910c8818.png)

but now i got no `bitmap()` method!

![selection_001](https://cloud.githubusercontent.com/assets/4931115/7523231/02b0f730-f503-11e4-94b4-9b05bee6f0a1.png)


is that's a personal problem or not from me?! :confused:

**Comment by atomfrede** [comment]
@MuhamedFathy You are importing the ``javase`` version. You need to depend on the ``android`` module:

```
dependencies {
    compile 'net.glxn.qrgen:android:2.1-SNAPSHOT'
}
```

**Comment by MuhamedFathy** [comment]
Now works great!
Thanks bro! :blush:

**Comment by atomfrede** [comment]
You're welcome.

**Comment by MuhamedFathy** [comment]
@atomfrede 
Sorry but i forgot something, what about `withColor()` method?!
