### ISSUE TITLE
withColor();

### ISSUE THREAD

**Issue by MuhamedFathy** [kenglxn/QRGen#51]
What about `withColor()` method in android?
why it's only available in java se version, and when it will be available in android?!

**Comment by atomfrede** [comment]
Oh you're right. Will try to add it.

**Comment by MuhamedFathy** [comment]
Okay, Thanks! :smiley:

**Comment by atomfrede** [comment]
You should keep the issue open until its really closed ;)

**Comment by MuhamedFathy** [comment]
Okay, sorry for that

**Comment by plakat** [comment]
Hi!

I may be missing something obvious, but I can't find the method withColor() in the library version downloaded via Maven either. I use this dependency:

<dependency>
    <groupId>net.glxn.qrgen</groupId>
    <artifactId>javase</artifactId>
    <version>2.0</version>
</dependency>

**Comment by kenglxn** [comment]
try the 2.1-SNAPSHOT version

**Comment by ajma** [comment]
I tried with 2.1-SNAPSHOT and I still don't see withColor

**Comment by atomfrede** [comment]
At the moment it's only available on javase not yet on Android.

**Comment by Botz** [comment]
Just made a pullRequest for this in #62
