### ISSUE TITLE
VCard force stop on android

### ISSUE THREAD

**Issue by MuhamedFathy** [kenglxn/QRGen#52]
VCard not working on SDK 10 gingerbread, forcebstop every time try to generate from it, `NoSuchMethodException`, I handled it but it's also not working, just give me the handled toast even the text fields not empty!

**Comment by kenglxn** [comment]
what version are you using?

**Comment by atomfrede** [comment]
The Android module is compiled against Android 4.x so it doesn't work on gingerbread.

**Comment by MuhamedFathy** [comment]
@kenglxn  I use this version `net.glxn.qrgen:android:2.1-SNAPSHOT`

and this is the exception:


`05-24 13:43:55.657      534-534/com.mEmoZz.qrgen E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: java.lang.System.lineSeparator
            at net.glxn.qrgen.core.vcard.VCard.toString(VCard.java:92)
            at net.glxn.qrgen.android.QRCode.from(QRCode.java:66)
            at com.mEmoZz.qrgen.MainActivity.vcardCore(MainActivity.java:255)
            at com.mEmoZz.qrgen.Tabs.VCardFragment$1.onClick(VCardFragment.java:35)
            at android.view.View.performClick(View.java:2485)
            at android.view.View$PerformClick.run(View.java:9080)
            at android.os.Handler.handleCallback(Handler.java:587)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)`

@atomfrede  Normal QR works on gingerbread, only the v card force stop, is there anyway to solve that?

**Comment by atomfrede** [comment]
@MuhamedFathy Ok, thats strange. It looks like ``System.lineSeperator()`` is not available on android. Will check it in the next couple of days.

**Comment by MuhamedFathy** [comment]
Okay, great.

**Comment by kenglxn** [comment]
System.lineSeparator was introduced in java 1.7.
You need to build with source level 1.7 which should be available in build tools 19 or newer.
See this stackoverflow for related answer: http://stackoverflow.com/questions/8578441/can-the-android-sdk-work-with-jdk-1-7/21700827#21700827

**Comment by MuhamedFathy** [comment]
You talking to me or Mr. Frederik?
If me, i already build my app with 1.7, or what actually you mean?
Sorry if i don't understand 'Am newbie in developing at all'.


![selection_001](https://cloud.githubusercontent.com/assets/4931115/7788216/6390e948-0232-11e5-88f3-bfceccfc1514.png)

**Comment by kenglxn** [comment]
@MuhamedFathy you need to make sure you have your project set up to build with java 1.7 features against android.

**Comment by MuhamedFathy** [comment]
I changed it and still have the same problem!

**Comment by atomfrede** [comment]
@MuhamedFathy  your module settings should like in the attached screenshots. Most important is that you use at least sdk 19. Both source and target must be java 1.7

![unbenannt](https://cloud.githubusercontent.com/assets/203401/7788517/a484480e-023d-11e5-89a7-ca02e4dbe501.png)

**Comment by MuhamedFathy** [comment]
Actually givers me error now because am using material design in my project, is there any other way?

**Comment by atomfrede** [comment]
You're talking about this project: https://github.com/MuhamedFathy/QRGenerator ?

The material tabs documentation says:
> It requires 14+ API and android support v7 (Toolbar)

But in your ``build.gradle`` you have ``minSdkVersion 10`` so try to change it to e.g. 19 which should fix your error with that material tabs library.

**Comment by MuhamedFathy** [comment]
This library works with gingerbread too, and i need to support it, any other way please? :/

**Comment by kenglxn** [comment]
you could try to fork QRGen and replace System.lineSeparator with System.getProperty("line.separator") or just "\n" and build it locally. If you do you should also change the version in the pom so you don't get your local version overridden by changes in the remote.
Also, to be sure you don't have other java 1.7 problems, you should change source and target version to 1.6 in the maven compiler plugin in the pom.

good luck.

**Comment by atomfrede** [comment]
@MuhamedFathy Not quite sure if the material tabs library is a good choice at the moment: 

> Hi! As all can see, this library has multiple problems. I'm working for redo all the code and publish an official release that is usable. This mean this current version is no longer maintained and I will not do any bug fix for it.

But yes, you can try to fork ``QRGen`` and then use jitpack.io to add your forked and modified version to your dependencies.

**Comment by kenglxn** [comment]
Closing this as it is not an issue with QRGen.

feel free to keep discussing, but no changes in QRGen will be made related to this.
