### ISSUE TITLE
Unable to compile on Android when another library use zxing

### ISSUE THREAD

**Issue by ilmetu** [kenglxn/QRGen#55]
Hi, 

my app need to create and read a qr code, so i get your awesome library and another one for scanning purpose: https://github.com/dlazaro66/QRCodeReaderView

but when i try to compile the compiler (Gradle - Android studio) failed :(

This is the error :
com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/BarcodeFormat; 

Do you have any idea to solve this problem ?

Thanks.

**Comment by kenglxn** [comment]
hmm. sounds like you are getting two conflicting versions of zxing.
Do you have a link to your code?

**Comment by ilmetu** [comment]
i can put my code online if helps you to find a solution, but it happens just when i put the dependencies in gradle :(

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
    compile 'net.glxn.qrgen:android:2.0'
}

the last two rows are the problem :(

Thanks.

**Comment by kenglxn** [comment]
Perhaps try to exclude zxing from one of them, or add it explicitly:

  dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.android.support:support-v4:22.2.0'
    compile ('com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0') {
       exclude group: 'org.zxing'
    }
  }

You have to look at gradle doc and the actual artifact to exclude, the example above is just pseudo code.

**Comment by kenglxn** [comment]
to add explicitly do someting like:

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.android.support:appcompat-v7:22.2.0'
        compile 'com.android.support:design:22.2.0'
        compile 'com.android.support:support-v4:22.2.0'
        compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
        compile 'net.glxn.qrgen:android:2.0'
        compile 'com.google.zxing:core:3.1.0'
    }

**Comment by kenglxn** [comment]
That module you're referring to defines its own classes in the com.google.zxing.client.android.common namespace. This will potentially also cause problems for you down the road.

**Comment by kenglxn** [comment]
You need to figure out where the other 'com/google/zxing/BarcodeFormat' definition is coming from. 
Gradle should handle this without issues in normal cases, so it may be coming from somewhere else.

**Comment by ilmetu** [comment]
Excluding the com.google.zxing from your library do the trick!  

  compile ('net.glxn.qrgen:android:2.0') {
        exclude group: 'com.google.zxing'
    }

Thanks man you are a pro!

**Comment by kenglxn** [comment]
Np. Glad to hear it worked out for you!
