### ISSUE TITLE
Substitute sonatype release setup for jitpack.io

### ISSUE THREAD

**Issue by kenglxn** [kenglxn/QRGen#61]
also change readme to reflect new setup

**Comment by atomfrede** [comment]
I'm very pleased with jitpack.io. But I guess it is more for development releases, but it is definitly veeeery easy (zero setup more or less)

**Comment by kenglxn** [comment]
nice, will check it out

**Comment by kenglxn** [comment]
Jitpack is the way to go. Thanks for the tip @atomfrede 
Will release next version using their guide very soon.

**Comment by LTheobald** [comment]
Placing this here incase anyone else struggles against Jitpack & Nexus like I have been: https://github.com/jitpack/jitpack.io/issues/506

**Comment by kenglxn** [comment]
Awesome! thank you. Will put this in the readme.

**Comment by vemv** [comment]
This is kind of a security risk, isn't it? I trust Maven Central way more than Jitpack - the former has been around for longer, has a greater too-big-to-fail factor.

Central artifact repos can always modify .jar contents with evil stuff.

My concern is particularly relevant for a QR-related library.

Hope you can give it some thought!

Thanks - V

**Comment by msgilligan** [comment]
I just got negative feedback (and possible rejection) of a PR because QRGen uses jitpack.io instead of Maven Central. I agree with @vemv that _release versions_ of QRGen should be released to Maven Central.

**Comment by allenluce** [comment]
Not sure how often this happens, but jitpack.io is currently down for me:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:javaPreCompileDevDebug'.
> Could not resolve all files for configuration ':app:devDebugCompileClasspath'.
   > Could not download android.jar (com.github.kenglxn.QRGen:android:2.5.0)
      > Could not get resource 'https://jitpack.io/com/github/kenglxn/QRGen/android/2.5.0/android-2.5.0.jar'.
         > Could not GET 'https://jitpack.io/com/github/kenglxn/QRGen/android/2.5.0/android-2.5.0.jar'. Received status code 521 from server: Origin Down
   > Could not download core.jar (com.github.kenglxn.QRGen:core:2.5.0)
      > Could not get resource 'https://jitpack.io/com/github/kenglxn/QRGen/core/2.5.0/core-2.5.0.jar'.
         > Could not GET 'https://jitpack.io/com/github/kenglxn/QRGen/core/2.5.0/core-2.5.0.jar'. Received status code 521 from server: Origin Down
```
Their [web page](https://jitpack.io ) is also affected:

![Screen Shot 2019-06-27 at 10 14 55 AM](https://user-images.githubusercontent.com/4258048/60286491-7f675080-98c4-11e9-8125-04702dab9377.png)

**Comment by kenglxn** [comment]
Hoping to get access to github package registry soon. That should resolve
these issues. Releasing to maven central is too much of a hassle. I will
have a look after the holidays to see if I can get an alternate solution
available in the interim.
-- 

Ken Gullaksen
http://glxn.net

**Comment by rzo1** [comment]
> I just got negative feedback (and possible rejection) of a PR because QRGen uses jitpack.io instead of Maven Central. I agree with @vemv that _release versions_ of QRGen should be released to Maven Central.

I agree with @msgilligan and @vemv . Why can't the _release versions_ of QRGen be released via Maven Central?

Proxying ` jitpack.io` on several build servers or on a custom JFrog artifactory is just **pain**.

**Comment by kenglxn** [comment]
Because publishing to maven central is cumbersome. I will try to resolve this issue when I get time in my schedule. I am looking for alternatives to jitpack.

**Comment by rzo1** [comment]
Thanks, @kenglxn for putting this on the schedule again. In addition, the `groupId` used in jitpack.io differs from the one used in the source code.

**Comment by Lonzak** [comment]
Any luck with putting this to maven central again? We have the same issue :-/

**Comment by szpak** [comment]
> Because publishing to maven central is cumbersome.

@kenglxn Could you elaborate more on that topic? Do you mean manual releasing from your computer and clicking in the Sonatype Nexus or rather making it possible to work automatically from your CI server?

**Comment by pvegh** [comment]
I'm not sure putting the complexity/risk/additional repository to every project is the correct step. I'd like to have dependencies only from maven central.
