### ISSUE TITLE
Execution failed for task ':app:transformClassesWithJarMergingForDebug'

### ISSUE THREAD

**Issue by kongsonida** [kenglxn/QRGen#66]
I got a problem when I used two libraries of QR-Code (Ready and Generator QR-Code) in gradle

 compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
 compile 'com.github.kenglxn.QRGen:android:2.1.0' 

=================== Gradle ===============
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.dlazaro66.qrcodereaderview:qrcodereaderview:1.0.0'
    compile 'com.github.kenglxn.QRGen:android:2.1.0' 
}

========== Message after run project failed ===============
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/google/zxing/BarcodeFormat.class

===================================

Please fix this issue

**Comment by kongsonida** [comment]
Please help as soon as possible

**Comment by atomfrede** [comment]
When you remove either the reader or generator the error is gone? 

I guess it has something to do with zxing used by both libraries. So try to exclude it for one of the dependencies in your gradle file. You can also try to enable multidex support for your build.

**Comment by kongsonida** [comment]
Yes, error is gone if I remove one of them.

Could you example to exclude in dependencies in gradle file ? because I tried many time, but I cannot do it...

Thanks in advance

**Comment by atomfrede** [comment]
Have a look at this [stackoverflow thread](http://stackoverflow.com/questions/33164107/error-after-adding-play-services-library-apptransformclasseswithjarmergingf) I think it should contain all answers to your problem

**Comment by ttyh061** [comment]
Hi, kongsonida,

When you use QRGen and qrcodereaderview together, you can exclude the xing lib used by QRGen as below:
   compile ('com.github.kenglxn.QRGen:android:2.1.0') {
        exclude group: 'com.google.zxing', module: 'core'
    }

**Comment by kenglxn** [comment]
As far as I can see this is not a bug in QRGen but a build setup issue.
