### ISSUE TITLE
"Padding" problem

### ISSUE THREAD

**Issue by Jayvd** [kenglxn/QRGen#67]
Hello. Thanks for providing a library that SIMPLE.

I have one question though. I am wondering if we can set the padding of the QR code and the background?

`QRCode.from("String to be encoded".withColor(Color.BLACK, Color.TRANSPARENT).withSize(512, 512);`

The BLACK is very small compared to the white background part. Is there anyway we could adjust this?

**Comment by kenglxn** [comment]
Did you figure this out? 
Could you elaborate?

**Comment by Jayvd** [comment]
Yes, I realized how simple it was. What I meant was the margin between the qr and it's background.
Easily done via `withHint()`

Thanks
