### ISSUE TITLE
Dimension behaves unpropotional

### ISSUE THREAD

**Issue by leolux** [kenglxn/QRGen#68]
The generated QR code never covers the complete image because the generator always adds some border around it. One issue is that the dimension of the QR code does behave propotional to the dimension of the target image including the border. The problem is when you change the size of the image by one pixel the size of the QR code gets increased by 10 pixel wheareas the border size gets decreased by 9 pixels. This is not propotional to a change by one pixel.

A reproducible example where the actual QR code gets a lot smaller by changeing the image size by only one pixel:
1. generate a QR code with the dimension 110x110 pixel
2. generate a QR code with the dimension 111x111 pixel

The difference is big:
![Image example](http://s17.postimg.org/90d9n5wxb/qr_Code_issue.png)

**Comment by kenglxn** [comment]
I don't think this is a bug, but rather how ZXING behaves as defined by the qr code specification. See this discussion which seems relevant https://groups.google.com/forum/m/#!topic/zxing/MFd8-3IxmVY

You may set a fixed margin which could work around the issue with EncodeHintType.MARGIN (https://zxing.github.io/zxing/apidocs/com/google/zxing/EncodeHintType.html). 

Either way I don't see this as an isdue with QRGen itself.
