### ISSUE TITLE
License compatibility issue

### ISSUE THREAD

**Issue by ducciovigolo** [kenglxn/QRGen#69]
Hi,
I've seen that under the hood your library is leveraging jfreesvg that is licensed under GPL v3.
This situation is compatible with the Apache 2 License of QRGen?
It seems that the 2 license are not compatible: http://www.apache.org/licenses/GPL-compatibility.html

I'm missing something?
Can I use your library in my commercial solution?

Thanks very much

Duccio

**Comment by kenglxn** [comment]
Thank you for making me aware of this issue. I will look into it, and either remove the functionality completely, or find a valid licensed alternative.

**Comment by kenglxn** [comment]
Considering the license incompatibility and the lack of a viable alternative, I think it is best to remove this feature completely. 

@ducciovigolo You could use an older pre 2.0 version to get around the license for now, for example v1.4. Or if you have time you could fork and fix it for me in a PR :)

**Comment by atomfrede** [comment]
@kenglxn As I am the one introduced svg support I can provide a PR.

**Comment by kenglxn** [comment]
@atomfrede Cool man. Thank you :)

**Comment by ducciovigolo** [comment]
@kenglxn, @atomfrede thank you very much for your answers and your time. 

@kenglxn I'll wait for the PR and a new version of your great library!

**Comment by ducciovigolo** [comment]
@kenglxn, @atomfrede thanks for your fix

@kenglxn any idea about the next release date? I would prefer to use a "official" build instead of a "self-made" one...

thank again

**Comment by atomfrede** [comment]
@ducciovigolo You can just use this dependency, its more or less like an official version.

```
<dependency>
	    <groupId>com.github.kenglxn</groupId>
	    <artifactId>QRGen</artifactId>
	    <version>-SNAPSHOT</version>
</dependency>
```

**Comment by kenglxn** [comment]
i'll get one out in the next couple of days, in the meantime you can use the commit hash https://jitpack.io/docs/#snapshots

**Comment by kenglxn** [comment]
@ducciovigolo here you go: https://jitpack.io/#kenglxn/QRGen/2.2.0
