### ISSUE TITLE
Cannot access repo

### ISSUE THREAD

**Issue by nesterov-n** [kenglxn/QRGen#70]
Try to use your library in my project.

build.gradle:

```
dependencies {
    ....
    compile 'com.github.kenglxn.QRGbuen:android:2.1.0'
    ....
}
```

When I buil my project I get error: 

`Error:Could not GET 'https://jitpack.io/com/github/kenglxn/QRGbuen/android/2.1.0/android-2.1.0.pom'. Received status code 401 from server: Repo not found or no access token provided`

**Comment by atomfrede** [comment]
You have a typo in your dependency.

Try ``compile 'com.github.kenglxn.QRGen:android:2.1.0'``

**Comment by nesterov-n** [comment]
Oh. Sorry for such stupid mistake. And thank you very much for your help.
