### ISSUE TITLE
support for other QR types

### ISSUE THREAD

**Issue by sytolk** [kenglxn/QRGen#72]
Its have only two types supported now (Text and VCard). If I open this page 
http://goqr.me/#t=call
on the point 1. its have 9 types: Call, URL, SMS, WIFI, Location.. is missing
I suppose that all types are string formatted with some tags like VCard.toString() but I cant find info for this?
I have found WiFi schema:
core/src/test/java/net/glxn/qrgen/core/scheme/WifiTest.java

Do you have schema for Call ? (phone number) 
I have found here http://sixrevisions.com/web-development/qr-codes-uri-schemes/
tel:<number>

this is very helpful
https://github.com/zxing/zxing/blob/master/core/src/test/java/com/google/zxing/client/result/ParsedReaderResultTestCase.java

it will be good if its have info in README for the different schema types. I can provide PR or this is better to be set with Enum before Text?

**Comment by kenglxn** [comment]
Sorry, no. Feel fre to submit a PR with it if you want :)

**Comment by kenglxn** [comment]
fixed by #93
