### ISSUE TITLE
Failed to resolve: com.github.kenglxn.QRGen:android:2.1.0  on android studio

### ISSUE THREAD

**Issue by solokingjec** [kenglxn/QRGen#73]
I added the following line "compile 'com.github.kenglxn.QRGen:android:2.1.0'" on my gradle file inside dependencies but I get this error Failed to resolve: com.github.kenglxn.QRGen:android:2.1.0

**Comment by atomfrede** [comment]
Have you added the required jitpack repository? 

```gradle
repositories { 
maven { url "https://jitpack.io" } 
}
```

**Comment by kenglxn** [comment]
Closing this. Does not seem to be an issue

**Comment by fadsel** [comment]
Coming back to this in **2020!** - good old jetpack.io always missing from the repos :dancer:

**Comment by kenglxn** [comment]
Still looking for an alternative. I am considering publishing to maven
central again. I will look into it soon.
-- 

Ken Gullaksen
http://glxn.net

**Comment by fadsel** [comment]
Looking forward to it, great work so far!

**Comment by kenglxn** [comment]
Just discovered packagecloud.io Perhaps a viable alternative: https://packagecloud.io/docs#maven_deploy
