### ISSUE TITLE
File.toPath() method not found in android.jar

### ISSUE THREAD

**Issue by onlynight** [kenglxn/QRGen#75]
i use the android-23 SDK,and set the build environment as JAVA_1_7. And i check the File.java it doesn't shows the method toPath method in File.java

**Comment by atomfrede** [comment]
That should not be an issue as ``toPath`` is only used in the ``javase`` module.

**Comment by kenglxn** [comment]
This is not an issue with QRGen, but a limitation in android sdk https://developer.android.com/reference/java/io/File.html
