### ISSUE TITLE
QR-Code white Border

### ISSUE THREAD

**Issue by Informaticore** [kenglxn/QRGen#76]
Is it possible to get rid of the white border arround the QR-Code?

**Comment by kenglxn** [comment]
You should be able to pass a hint to zxing. see http://zxing.github.io/zxing/apidocs/com/google/zxing/EncodeHintType.html#MARGIN

Something like: `QRCode.from("Hello World").withHint(EncodeHintType.MARGIN, "1");`

Keep in mind that this could affect the decode ability of some clients.
