### ISSUE TITLE
image overlay

### ISSUE THREAD

**Issue by maz1987in** [kenglxn/QRGen#77]
Could you please adds a image overlay to a qrcode?

**Comment by kenglxn** [comment]
Interesting idea, found this article that looks promising https://skrymerdev.wordpress.com/2012/09/22/qr-code-generation-with-zxing/

**Comment by paulvi** [comment]
@kenglxn The generated QRCode from https://skrymerdev.wordpress.com/2012/09/22/qr-code-generation-with-zxing/ cannot be read, so the article is actually shows wrong approach.

**Comment by kenglxn** [comment]
Thanks for trying and letting us know @paulvi

**Comment by kenglxn** [comment]
Although interesting, probably not a good idea. Killing this for now.
