### ISSUE TITLE
Exception in Rendring

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [kenglxn/QRGen#78]
GMPM: getGoogleAppId failed with status: 10
GMPM: Uploading is not possible. App measurement disabled
AndroidRuntime: FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: net.glxn.qrgen.android.QRCode

**Comment by kenglxn** [comment]
Looks like a project setup problem. I can not see how this could be an issue with QRGen.
