### ISSUE TITLE
Invalid maven groupid

### ISSUE THREAD

**Issue by marcolenzo** [kenglxn/QRGen#79]
The `groupid` for your artifact in Maven seems to be `com.github.kenglxn.QRGen`. I know this is a minor thing but it took me some time to realize since in your documentation you state it as `com.github.kenglxn.qrgen`.

**Comment by marcolenzo** [comment]
Actually I must have some other issue because I am not managing to pull the artifact either way.

**Comment by atomfrede** [comment]
Have you added the ``jitpack`` repo? The artifact id is ``com.github.kenglxn.QRGen:javase:2.2.0`` for the ``javase`` submodule

**Comment by kenglxn** [comment]
Closing this. The group-id is correct in the readme.
