### ISSUE TITLE
Support for Wi-Fi Enterprise

### ISSUE THREAD

**Issue by Fleker** [kenglxn/QRGen#82]
Right now it seems like your [Wi-Fi QR code generator](https://github.com/kenglxn/QRGen/blob/master/core/src/main/java/net/glxn/qrgen/core/scheme/Wifi.java) only supports WEP and WPA, but not enterprise (where there's both a username and password).

I propose adding support for enterprise level Wi-Fi based on [this guide](http://www.glassappsource.com/google-glass-how-to/connect-enterprise-wpa-network-google-glass.html).

**Comment by kenglxn** [comment]
fixed by #83
