### ISSUE TITLE
2.2.0 not found

### ISSUE THREAD

**Issue by typ0520** [kenglxn/QRGen#84]
jcenter上只有2.0这个版本 ,README里写的是2.2.0，是README写错了，还是jar包没有传
https://jcenter.bintray.com/net/glxn/qrgen/javase/

**Comment by atomfrede** [comment]
It is not published to jcenter or central anymore. You have to use the jitpack repository. When using maven add this repository:
```xml
 <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```

and use this artifact:
```xml
<dependencies>
        <dependency>
            <groupId>com.github.kenglxn.qrgen</groupId>
            <artifactId>javase</artifactId>
            <version>2.2.0</version>
        </dependency>
    </dependencies>
```

For details see the ``README``
