### ISSUE TITLE
cannot resolve

### ISSUE THREAD

**Issue by maoxiao** [kenglxn/QRGen#85]
I added compile 'com.github.kenglxn.QRGen:javase:2.2.0' to my android project. However, I ended up getting an error says "Failed to resolve github.kenglxn.QRGen:javase:2.2.0". Is there any other dependency should be added?

**Comment by atomfrede** [comment]
Have you added the required jitpack repository to your `build.gradle`?

```grovvy
 allprojects {
        repositories {
            // ...
            maven { url "https://jitpack.io" }
        }
    }
```

**Comment by maoxiao** [comment]
@atomfrede Thank you for your help!   It is resolved!
