### ISSUE TITLE
unable to resolve with android latest version

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [kenglxn/QRGen#90]
hi, i've updated my app and getting error after upgrading from 25 to 26, please help me to sort out this issue 

![untitled](https://user-images.githubusercontent.com/4646811/30404033-f4ec3d98-98fd-11e7-979b-0c09a3f58dee.png)
compileSdkVersion 26
buildToolsVersion "26.0.1"

**Comment by kenglxn** [comment]
how are you adding the dependency? can you show us the buil file?
make sure you have set up the repository as described in the readme?

**Comment by kenglxn** [comment]
@abdulrahmanmajeed I want to confirm this is an issue with QRGen. Could you give some more details as requested above?

**Comment by kenglxn** [comment]
closing this as it seems unrelated to QRGen. Feel free to reopen if it indeed is a bug. We will need details on the build setup and steps to reproduce to debug/solve it.

**Comment by prashantkbhardwaj** [comment]
Hi, I am facing the same issue, can you please help me with this?

**Comment by atomfrede** [comment]
You should provide more information. Can you share your build.gradle file?

**Comment by prashantkbhardwaj** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "com.example.prashantbhardwaj.cloudadicscanner"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.github.kenglxn.QRGen:android:2.3.0'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}

**Comment by atomfrede** [comment]
You beed to add the required `jitpack` repository:
```gradle
repositories {
  maven { url "https://jitpack.io" }
}
```

**Comment by prashantkbhardwaj** [comment]
Where do I add this?

**Comment by prashantkbhardwaj** [comment]
Okay, got it. Thanks a lot
