### ISSUE TITLE
Failed to resolve 

### ISSUE THREAD

**Issue by Ramkesh9** [kenglxn/QRGen#91]
Error:(32, 13) Failed to resolve: com.github.kenglxn.QRGen:android:2.3.0
<a href="openFile:/Users/ricky/Workspace/QrGenrater/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by atomfrede** [comment]
Have you added the jitpack repository as described in the readme?

**Comment by Ramkesh9** [comment]
no actually I am new in android, so please assist me
