### ISSUE TITLE
Suggestion on how to remove image padding?

### ISSUE THREAD

**Issue by andrevdk** [kenglxn/QRGen#97]
I am using this library on Android and the generated bitmap has a big padding. Is there any way to remove it before the generation of the bitmap?

**Comment by kenglxn** [comment]
You should be able to control padding through hints (https://zxing.github.io/zxing/apidocs/com/google/zxing/EncodeHintType.html):
```
QRCode.from("Hello World").withHint(EncodeHintType.MARGIN, 2)
```
